[build]
  command = "npm run build"  # Use your actual build command (e.g., npm run build)
  functions = "netlify/functions"  # If you have serverless functions
  publish = "build"  # Use the directory where your built files are

# Optional redirects for single-page applications (uncomment if needed)
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# Optional settings for Netlify Dev (uncomment and modify as needed)
# [dev]
#   command = "npm start"  # Use your development server command
#   port = 3000
#   publish = "build"  # Same as your build publish directory
